### PR TITLE
Return the path and add methods to get a device by path or id

### PR DESCRIPTION
**Pull request by peternewman**
Also includes #4

### CODE REVIEW

**Comment by hopejr** [comment]
These changes look good to me.

**Comment by hopejr** [comment]
What sort of checks do you want to do with the TODO in the tests file? I'd like to merge this without a TODO in it if possible.

**Comment by peternewman** [comment]
> What sort of checks do you want to do with the TODO in the tests file? I'd like to merge this without a TODO in it if possible.

I'm not really sure, I guess fetch the path or at least model name from the HID info to make sure it hasn't say returned the mouse or something.

**Comment by peternewman** [comment]
Are you happy with that @hopejr ?

**Comment by hopejr** [comment]
Would the check for "Shuttle" work with the newer names? I guess it probably would because it's still the same device, but I don't know if they could've changed it in the device itself.

**Comment by hopejr** [comment]
Actually, it's just a test, so that wouldn't matter.

**Comment by hopejr** [comment]
Have a look at the commit I just made on this PR and see if that's what you're wanting (addressing issue  #6). If so, I'll merge it in (with an updated README.md file).

**Comment by peternewman** [comment]
> Have a look at the commit I just made on this PR and see if that's what you're wanting (addressing issue #6). If so, I'll merge it in (with an updated README.md file).

Yeah that looks good thanks. Is it worth adding a test for this too?

**Comment by peternewman** [comment]
> Would the check for "Shuttle" work with the newer names? I guess it probably would because it's still the same device, but I don't know if they could've changed it in the device itself.

> Actually, it's just a test, so that wouldn't matter.

Yeah I'd half meant to add a comment in the test to extend the regex if required.

**Comment by hopejr** [comment]
> > Have a look at the commit I just made on this PR and see if that's what you're wanting (addressing issue #6). If so, I'll merge it in (with an updated README.md file).
> 
> Yeah that looks good thanks. Is it worth adding a test for this too?

It's a constant enum. Not sure that it needs a test?

**Comment by peternewman** [comment]
> It's a constant enum. Not sure that it needs a test?

Fair enough, I was just thinking to check it's being exported and it's got the right value.

**Pull request merged**
