### PR TITLE
Update README.md - Try and better clarify that serial or path will be hashed

### PR DESCRIPTION
**Pull request by peternewman**
Probably needs an Oxford comma!

### CODE REVIEW

**Comment by hopejr** [comment]
Much better. Documentation isn't my strong point. :P

**Comment by peternewman** [comment]
Or alternatively something like:
`either the serial number (if it exists) or the device path, turned into an MD5 hash, used to distinguish between multiple devices that may be connected at once.`

**Comment by hopejr** [comment]
> Or alternatively something like:
> `either the serial number (if it exists) or the device path, turned into an MD5 hash, used to distinguish between multiple devices that may be connected at once.`

That is more what I was trying to say in the first place. Let's go with that.

**Comment by peternewman** [comment]
> That is more what I was trying to say in the first place. Let's go with that.

Now all updated with the alternative wording.

**Pull request merged**
