### PR TITLE
Add old shuttle pro (aka V1)

### PR DESCRIPTION
**Pull request by checksummaster**
Old shuttle pro (aka V1)

### CODE REVIEW

**Comment by hopejr** [comment]
Does the Shuttle Pro v1 have 16 buttons too? I thought it was only 15.

**Comment by checksummaster** [comment]
As I understand, v2 add two button on the side of the shuttle, v1 have 13
buttons (9 on top and 4 on bottom) and v2 have 15 (one on each side).

I think mask value are same (for common buttons) but I don't have anymore
the v2 version to check it ...

I already wrote my own driver for embedded system long time ago for v1 and
v2.

**Comment by hopejr** [comment]
Sorry, I forgot it was only 15 on v2. It's been a while since I've looked at this. Do you know what the button masks for v1 are? It would be good to remove any of the v2 ones that aren't on v1 from it's list.

**Comment by checksummaster** [comment]
I try to make it visually. values are bit position or "mask = 1 <<
(value-1)". EI 1 = 1, 13 = 4096.

   1   2    3    4
5    6   7    8    9

x     (shuttle)    x         (x = no button .... version 2 have)

10                  11
   12            13

**Comment by hopejr** [comment]
Ok, then we'll need to change the masks array to:
[0x0001, 0x0002, 0x0004, 0x0008, 0x0010, 0x0020, 0x0040, 0x0080, 0x0100, 0x0200, 0x0400, 0x0800, 0x1000]

(Minus the 0x2000 and 0x4000 at the end).

**Comment by hopejr** [comment]
I've just updated the button masks, as well as the readme, etc. Will merge this now. Thank you for the PR.

**Pull request merged**
